<html>
<head>
<base href="<?php echo base_url();?>"/>
<link rel="stylesheet" href="assets/css/rspdf.css?<?php echo time(); ?>">  
</head>
<body>
<div class="main">
	<div class="row center">
		<p class="title">Pluxee Philippines Incorporated</p>
		<p>8747 Paseo de Roxas Street, 11TH Floor, B.A. Lepanto Condominium, Makati City (1200), Metro Manila, Philippines </p>
		<p>Tel. no: 8689-4700. Fax no: 86894777</p>
		<p>TIN: 223-183-726-00000 </p>
	</div>
	<?php 
	foreach($branchInfoRS  as $mer_row):
		$REIMBURSEMENT_DATE = $mer_row->REIMBURSEMENT_DATE;
		$EXPECTED_DUEDATE = $mer_row->ExpectedDueDate;
		$REIMBURSEMENT_USER = $mer_row->full_name;
	?>
	<div class="row center">
		<p class="title">REIMBURSEMENT SUMMARY REPORT</p>
	</div>
	
	<div class="row">
		<table class="tbl">
			<tr>
				<td class="tbl_title">Generation Date and Time:</td>
				<td><?php echo $REIMBURSEMENT_DATE?></td>
				<td class="tbl_title">Processed by:</td>
				<td><?php echo $mer_row->full_name?></td>
			</tr>				
			<tr>
				<td class="tbl_title">TIN:</td>
				<td colpan="3"><?php echo $mer_row->TIN?></td>
			</tr>			
			<tr>
				<td class="tbl_title">Merchant Name:</td>
				<td colpan="3"><?php echo $mer_row->LegalName?></td>
			</tr>			
			<tr>
				<td class="tbl_title">BRANCH:</td>
				<td colpan="3"><?php echo $mer_row->BRANCH_NAME?></td>
			</tr>			
			<tr>
				<td class="tbl_title">RS Number:</td>
				<td colpan="3"><?php echo $mer_row->RS_NUMBER?></td>
			</tr>
	
		</table>
	</div>
	<?php endforeach;?>
	<div class="block_row">
		<table class="tbl_2">
			<thead>
				<tr>
					<td>Service</td>
					<td class="center">Denomination</td>
					<td class="center">Qty</td>
					<td class="number">Total Face Value</td>
				</tr>
			</thead>
			<tbody>
			<?php 
			$sumQTY= $sumFV = 0;
			foreach($rsLi  as $br_row):
			?>
			<tr>
				<td><?php echo $br_row->SERVICE_NAME?></td>
				<td class="center"><?php echo number_format($br_row->DENO)?></td>
				<td class="center"><?php echo number_format($br_row->QTY)?></td>
				<td class="number"><?php echo number_format($br_row->TOTAL_FV, 2)?></td>
			</tr>
			<?php 			
				$sumFV += $br_row->TOTAL_FV;
				$sumQTY += $br_row->QTY;
			endforeach;					
			?>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2"></td>
					<td class="center bordertop"><?php echo number_format($sumQTY)?></td>
					<td class="number bordertop"><?php echo number_format($sumFV, 2)?></td>
				</tr>
			</tfoot>
		</table>
	</div>

	<div class="row">
		<div class="sum_left">
			<p>Approved By:</p>
			<p class="sign_box">Jun Domingo / Benjamin Nadala</p>
		</div>
	</div>	

	<div class="row">
		<table class="tbl">
		<tr>
			<td class="tbl_title">Generated by:</td>
			<td><?php echo $REIMBURSEMENT_USER?></td>
			<td class="tbl_title">Printed by:</td>
			<td><?php echo $data_user->full_name;?></td>
		</tr>	
		<tr>
			<td class="tbl_title">Date Generated:</td>
			<td><?php echo $REIMBURSEMENT_DATE?></td>
			<td class="tbl_title">Date Printed: </td>
			<td><?php echo $date_printed?></td>
		</tr>
		</table>
	</div>
	
	<div class="row">
		<p class="center">
		<?php if($copy == false):?>
			ORIGINAL COPY OF PAYMENT ADVICE
		<?php else:?>		
			PRINTED COPY OF PAYMENT ADVICE
		<?php endif;?>	
		</p>
	</div>
</div>

</body>
