-- Migration: Add missing columns to redemption table
-- Fixes: Unknown column errors when inserting via /redeem upload
-- Columns added: MERCHANT_NAME, TRANSACTION_ID, SOURCE_FILE

ALTER TABLE `redemption`
  ADD COLUMN IF NOT EXISTS `MERCHANT_NAME` VARCHAR(250) NOT NULL DEFAULT '' AFTER `REDEEM_ID`,
  ADD COLUMN IF NOT EXISTS `TRANSACTION_ID` VARCHAR(100) NOT NULL DEFAULT '' AFTER `PROD_ID`,
  ADD COLUMN IF NOT EXISTS `SOURCE_FILE`    VARCHAR(255) NOT NULL DEFAULT '' AFTER `PAYMENT_MODE`;
