-- Migration: Add missing columns to reconcilation table
-- Fixes: Unknown column errors when inserting via /recon/upload_recon/evoucher_recon
-- Columns added: MERCHANT_NAME, POS_ID, POS_TXN_ID, VOUCHER_CODE, SOURCE_FILE

ALTER TABLE `reconcilation`
  ADD COLUMN IF NOT EXISTS `MERCHANT_NAME` VARCHAR(250) NOT NULL DEFAULT '' AFTER `REDEEM_ID`,
  ADD COLUMN IF NOT EXISTS `POS_ID`        VARCHAR(100) NOT NULL DEFAULT '' AFTER `BRANCH_ID`,
  ADD COLUMN IF NOT EXISTS `POS_TXN_ID`   VARCHAR(100) NOT NULL DEFAULT '' AFTER `POS_ID`,
  ADD COLUMN IF NOT EXISTS `VOUCHER_CODE`  VARCHAR(100) NOT NULL DEFAULT '' AFTER `POS_TXN_ID`,
  ADD COLUMN IF NOT EXISTS `SOURCE_FILE`   VARCHAR(255) NOT NULL DEFAULT '' AFTER `PA_TEMPID`;
