<?php
class Corepass_model extends CI_Model{
	public $oracle_db;	
	public function __construct(){
		parent::__construct();
		// -- reminder: connection uat environment -- //
		$this->oracle_db = $this->load->database('oracle', TRUE);
	}
	
	/**
	 * getQueryClient function
	 *
	 * QUERY ACTION FOR COREPASS CLIENT
	 */
	public function getQueryClient($where = ''){
		/**
		 * ECGDP.TAXAPPLICATIONTYPE_ID as VATCond,
		 */
		$result = $this->oracle_db->query("SELECT 
				CP_ID,
				TIN,
				LegalName, 
				TradingName,
				GroupTIN,
				GroupName,
				MerchantFee,
				VATCond,
				Industry,
				MeanofPayment,
				BankName,
				BankAccountNumber,
				BankBranchCode,
				PayeeName,
				PayeeCode,
				Address,
				PayeeQtyOfDays,
				PayeeDayType,
				PayeeComments,
				AffiliateGroupCode,
				AGREEMENT_ID
		FROM
		(
			SELECT 
				EC.COMPANY_ID as CP_ID,
				ECGD.FISCAL_ID as TIN,
				ECGD.LEGALNAME as LegalName, 
				ECGD.FANTASYNAME as TradingName,
				ECGDP.GROUP_TIN as GroupTIN,
				ECGDP.GROUP_NAME as GroupName,
				ECGDP.N_WHTAXFEE as MerchantFee,
				MARKETING_FEE.VATCond as VATCond,
				COMPANY_INDUSTRY.COMPANY_INDUSTRY as Industry,
				EMLS_EMOPT.DEFAULTVALUE as MeanofPayment,
				BANK_INFO.DEFAULTVALUE as BankName,
				BANK_INFO.BANKACCOUNTNUMBER as BankAccountNumber,
				BANK_INFO.BANKCODE as BankBranchCode,
				EFCP.PAYEENAME as PayeeName,
				EFCP.PAYEECODE as PayeeCode,
				EFCP.GROUPCODE as AffiliateGroupCode,
				EIP.CONTACTPOSTALDATA_ID AS Address,
				EFC.Q_DAYSTOBEEFFECTIVE as PayeeQtyOfDays,
				EFC.DAYSCOUNTINGTYPE_ID PayeeDayType,
				EFC.COMMENTS PayeeComments,
				EA.AGREEMENT_ID
				FROM E_AFFILIATE_AGREEMENT EAA,
				E_AGREEMENT EA,
				E_AGREEMENT_GENERAL_DATA EAGD,
				E_COMPANY EC,
				E_COMPANY_GENERAL_DATA ECGD,
				E_COMPANY_GENERAL_DATA_PH ECGDP,
				E_DAYS_COUNTING_TYPE EDCT,
				E_FINANCIAL_CONDITION EFC,
				E_FINANCIAL_CONDITION_PH EFCP,
				E_MEAN_OF_PAYMENT EMOP,
				E_MEAN_OF_PAYMENT_TYPE EMOPT,
				E_MULTI_LANGUAGE_STRING EMLS_EDCT,
				E_MULTI_LANGUAGE_STRING EMLS_EMOPT,
				E_MULTI_LANGUAGE_STRING EMLS_EPSTP,
				E_MULTI_LANGUAGE_STRING EMLS_ES,
				E_PAYMENT_SUBM_TYPE_PH EPSTP,
				E_SERVICE ES,
				E_INVOICING_POINT EIP,
				(SELECT ECGD.FISCAL_ID,
				EMLS_ECG.DEFAULTVALUE AS COMPANY_INDUSTRY
				FROM E_COMPANY_GENERAL_DATA ECGD,
				E_COMPANY_COMPANY_GROUP ECCG,
				E_COMPANY_GROUP ECG,
				E_MULTI_LANGUAGE_STRING EMLS_ECG
				WHERE ECGD.COMPANYGENERALDATA_ID = ECCG.COMPANYGENERALDATA_ID
				AND ECCG.COMPANYGROUP_ID = ECG.COMPANYGROUP_ID
				AND ECG.NAME_ID = EMLS_ECG.STRING_ID
				AND ECG.COMPANYGROUPTYPE_ID = 1) COMPANY_INDUSTRY,
				(SELECT EA.AGREEMENT_ID,
				EMFTR.A_BASERANGE || ' - ' || EMFTR.N_PERCENTAGE * 100 || ' %' AS N_PERCENTAGE,
				ETXPH.TAXINCLUSIONTYPE_ID VATCond
				FROM E_AGREEMENT EA,
				E_BILLING_RULE EBR,
				E_BILLING_RULE_SET EBRS,
				E_BILLING_RULE_SET_BILL_RULE EBRSBR,
				E_FACE_VALUE_BILL_RULE EFVBR,
				E_MONEY_FILTER_TABLE EMFT,
				E_MONEY_FILTER_TABLE_ROW EMFTR,
				E_TAX_CONDITION_PH ETXPH
				WHERE EA.BILLINGRULESET_ID = EBRS.BILLINGRULESET_ID
				AND EBRS.BILLINGRULESET_ID = EBRSBR.BILLINGRULESET_ID
				AND EBRSBR.BILLINGRULE_ID = EBR.BILLINGRULE_ID
				AND EBR.BILLABLEITEMCATEGORY_ID = 5
				AND EBR.BILLINGRULE_ID = EFVBR.BILLINGRULE_ID
				AND EFVBR.MONEYFILTERTABLE_ID = EMFT.MONEYFILTERTABLE_ID
				AND EMFT.MONEYFILTERTABLE_ID = EMFTR.MONEYFILTERTABLE_ID
				AND EBR.TAXCONDITION_ID = ETXPH.TAXCONDITION_ID)MARKETING_FEE,
				(SELECT EBDM.MEANOFPAYMENT_ID,
				EMLS_EB.DEFAULTVALUE,
				EMLS_EBDT.DEFAULTVALUE AS ACCOUNTTYPE,
				EBA.BANKACCOUNTNUMBER,
				EB.CODE BANKCODE
				FROM E_BANK EB,
				E_BANK_ACCOUNT EBA,
				E_BANK_DEPOSIT_MOP EBDM,
				E_BANK_DEPOSIT_TYPE EBDT,
				E_MULTI_LANGUAGE_STRING EMLS_EB,
				E_MULTI_LANGUAGE_STRING EMLS_EBDT
				WHERE EBDM.BANKACCOUNT_ID = EBA.BANKACCOUNT_ID
				AND EBA.BANK_ID = EB.BANK_ID
				AND EB.NAME_ID = EMLS_EB.STRING_ID
				AND EBDM.BANKDEPOSITTYPE_ID = EBDT.BANKDEPOSITTYPE_ID
				AND EBDT.NAME_ID = EMLS_EBDT.STRING_ID) BANK_INFO
				WHERE EAA.AGREEMENT_ID = EA.AGREEMENT_ID
				AND EA.COMPANY_ID = EC.COMPANY_ID
				AND EC.COMPANYGENERALDATA_ID = ECGD.COMPANYGENERALDATA_ID
				AND ECGD.COMPANYGENERALDATA_ID = ECGDP.COMPANYGENERALDATA_ID
				AND ECGD.FISCAL_ID = COMPANY_INDUSTRY.FISCAL_ID(+)
				AND EA.AGREEMENTGENERALDATA_ID = EAGD.AGREEMENTGENERALDATA_ID
				AND EA.SERVICE_ID = ES.SERVICE_ID
				AND ES.NAME_ID = EMLS_ES.STRING_ID
				AND EA.AGREEMENT_ID = MARKETING_FEE.AGREEMENT_ID(+)
				AND EAA.REIMBURSEMENTCONDITIONS_ID = EFC.FINANCIALCONDITION_ID
				AND EFC.FINANCIALCONDITION_ID = EFCP.FINANCIALCONDITION_ID
				AND EFC.DAYSCOUNTINGTYPE_ID = EDCT.DAYSCOUNTINGTYPE_ID
				AND EDCT.NAME_ID = EMLS_EDCT.STRING_ID
				AND EFC.MEANOFPAYMENT_ID = EMOP.MEANOFPAYMENT_ID
				AND EMOP.MEANOFPAYMENTTYPE_ID = EMOPT.MEANOFPAYMENTTYPE_ID
				AND EMOPT.NAME_ID = EMLS_EMOPT.STRING_ID
				AND EMOP.MEANOFPAYMENT_ID = BANK_INFO.MEANOFPAYMENT_ID(+)
				AND EFCP.PAYMENTSUBMISSIONTYPE_ID = EPSTP.PAYMENTSUBMISSIONTYPE_ID
				AND EPSTP.NAME_ID = EMLS_EPSTP.STRING_ID
				AND EA.AGREEMENT_ID = EIP.AGREEMENT_ID
				AND EC.B_ACTIVE = 'T'
				AND ECGD.B_MOBILEVOUCHERPARTNER = 'T'
				and EA.SERVICE_ID = 27
				".$where."
				ORDER BY EC.COMPANY_ID
		)
		GROUP BY CP_ID,
				TIN,
				LegalName, 
				TradingName,
				GroupTIN,
				GroupName,
				MerchantFee,
				VATCond,
				Industry,
				MeanofPayment,
				BankName,
				BankAccountNumber,
				BankBranchCode,
				PayeeName,
				PayeeCode,
				Address,
				PayeeQtyOfDays,
				PayeeDayType,
				PayeeComments,
				AffiliateGroupCode,
				AGREEMENT_ID
		ORDER BY CP_ID ASC");
		return $result;
	}
	
	/**
	 * getQueryAddress function
	 *
	 * QUERY ACTION FOR COREPASS CLIENT
	 */
	public function getQueryAddress($addressID){
		/**
		 * 
		 */
		$result = $this->oracle_db->query("SELECT contactDataId, ADDRESS
				FROM
				(
					SELECT ECD.CONTACTDATA_ID AS contactDataId,
					EPCD.DOOR || EPCD.THOROUGHFARENAME || ' ' ||EPCD.THOROUGHFAREPOINT || ' ' ||	EMLS_ER1.DEFAULTVALUE || ' ' ||
					(SELECT defaultvalue FROM e_multi_language_string WHERE string_id=ER2.NAME_ID and ER2.REGIONTYPE_ID = 3) || ' ' ||
					(SELECT mls.defaultvalue FROM e_multi_language_string mls, E_REGION ER3 WHERE ER2.PARENT_ID = ER3.REGION_ID and mls.string_id=ER3.NAME_ID and ER3.REGIONTYPE_ID = 1) ADDRESS
					FROM 
					E_CONTACT_DATA ECD,
					E_POSTAL_CONTACT_DATA EPCD,
					E_THOROUGHFARE_TYPE TFT,
					E_REGION ER1,
					E_REGION ER2,
					E_MULTI_LANGUAGE_STRING EMLS_ER1,
					E_MULTI_LANGUAGE_STRING EMLS_TFT
					WHERE 
					ECD.CONTACTDATA_ID = EPCD.CONTACTDATA_ID
					AND EPCD.LOCALITY = ER1.REGION_ID
					AND ER1.NAME_ID = EMLS_ER1.STRING_ID
					AND ER1.PARENT_ID = ER2.REGION_ID
					AND EPCD.THOROUGHFARETYPE_ID = TFT.THOROUGHFARETYPE_ID
					AND TFT.NAME_ID = EMLS_TFT.STRING_ID
					AND ECD.CONTACTDATA_ID = ".$addressID."
				)
				GROUP BY contactDataId, ADDRESS
				ORDER BY contactDataId ASC");
		return $result;
	}

	/**
	 * getQueryAddress function
	 *
	 * QUERY ACTION FOR COREPASS CLIENT
	 */
	public function getQueryPeople($peopleID){
		/**
		 * 
		 */
		$result = $this->oracle_db->query("SELECT peopleId, ADDRESS
				FROM
				(
					SELECT distinct ECP.PEOPLE_ID peopleId,
					EPP.NAME || ' ' || EPP.lastname ContactPerson
					FROM 
					E_COMPANY_PERSON ECP,
					E_GROUP_PEOPLE EGP,  
					E_PHYSICAL_PERSON EPP
					WHERE 
					ECP.PEOPLE_ID = EGP.PEOPLE_ID
					AND EPP.PHYSICALPERSON_ID = ECP.PHYSICALPERSON_ID
					and ECP.PEOPLE_ID = ".$peopleID."
					ORDER BY ECP.PEOPLE_ID ASC
				)
				GROUP BY peopleId, ContactPerson
				ORDER BY peopleId ASC");
		return $result;
	}
	
	/**
	 * getQueryService function
	 *
	 * QUERY ACTION FOR COREPASS SERVICE
	 */
	public function getQueryService(){
		$result = $this->oracle_db->query("SELECT 
			s.SERVICE_ID AS service_id
			,mls.DEFAULTVALUE AS service_name
		FROM
			E_SERVICE s
			,E_MULTI_LANGUAGE_STRING mls
		WHERE
			s.NAME_ID=mls.STRING_ID
			AND s.B_ACTIVE = 'T'
		ORDER BY s.SERVICE_ID ASC");
				return $result;
	}
	
	/**
	 * getQueryPaymentCon function
	 *
	 * QUERY ACTION FOR COREPASS ACCOUNT PEOPLE ID
	 */
	public function getQueryPaymentCon($agrID){
		if(empty($agrID)) return '';
		$result = $this->oracle_db->query("SELECT 
				CP_ID,
				TIN,
				LegalName, 
				TradingName,
				GroupTIN,
				GroupName,
				MerchantFee,
				VATCond,
				Industry,
				MeanofPayment,
				BankName,
				BankAccountNumber,
				PayeeName,
				PayeeCode,
				PayeeId,
				AffiliateGroupCode,
				PayeeQtyOfDays,
				PayeeDayType,
				PayeeComments,
				Address
		FROM
		(
			SELECT 
				EC.COMPANY_ID as CP_ID,
				ECGD.FISCAL_ID as TIN,
				ECGD.LEGALNAME as LegalName, 
				ECGD.FANTASYNAME as TradingName,
				ECGDP.GROUP_TIN as GroupTIN,
				ECGDP.GROUP_NAME as GroupName,
				ECGDP.N_WHTAXFEE as MerchantFee,
				ECGDP.TAXAPPLICATIONTYPE_ID as VATCond,
				COMPANY_INDUSTRY.COMPANY_INDUSTRY as Industry,
				EMLS_EMOPT.DEFAULTVALUE as MeanofPayment,
				BANK_INFO.DEFAULTVALUE as BankName,
				BANK_INFO.BANKACCOUNTNUMBER as BankAccountNumber,
				BANK_INFO.ACCOUNTTYPE as BankAccountType,
				EFCP.PAYEENAME as PayeeName,
				EFCP.PAYEECODE as PayeeCode,
				EFCP.PAYEE_ID as PayeeId,
				EFCP.GROUPCODE as AffiliateGroupCode,
				EFC.Q_DAYSTOBEEFFECTIVE PayeeQtyOfDays,
				EMLS_EDCT.DEFAULTVALUE PayeeDayType,
				EFC.COMMENTS PayeeComments,			
				EIP.CONTACTPOSTALDATA_ID AS Address
				FROM 
				E_AFFILIATE_AGREEMENT EAA,
				E_AGREEMENT EA,
				E_AGREEMENT_GENERAL_DATA EAGD,
				E_COMPANY EC,
				E_COMPANY_GENERAL_DATA ECGD,
				E_COMPANY_GENERAL_DATA_PH ECGDP,
				E_DAYS_COUNTING_TYPE EDCT,
				E_FINANCIAL_CONDITION EFC,
				E_FINANCIAL_CONDITION_PH EFCP,
				E_MEAN_OF_PAYMENT EMOP,
				E_MEAN_OF_PAYMENT_TYPE EMOPT,
				E_MULTI_LANGUAGE_STRING EMLS_EDCT,
				E_MULTI_LANGUAGE_STRING EMLS_EMOPT,
				E_MULTI_LANGUAGE_STRING EMLS_EPSTP,
				E_MULTI_LANGUAGE_STRING EMLS_ES,
				E_PAYMENT_SUBM_TYPE_PH EPSTP,
				E_SERVICE ES,
				E_INVOICING_POINT EIP,
				(SELECT ECGD.FISCAL_ID,
				EMLS_ECG.DEFAULTVALUE AS COMPANY_INDUSTRY
				FROM E_COMPANY_GENERAL_DATA ECGD,
				E_COMPANY_COMPANY_GROUP ECCG,
				E_COMPANY_GROUP ECG,
				E_MULTI_LANGUAGE_STRING EMLS_ECG
				WHERE ECGD.COMPANYGENERALDATA_ID = ECCG.COMPANYGENERALDATA_ID
				AND ECCG.COMPANYGROUP_ID = ECG.COMPANYGROUP_ID
				AND ECG.NAME_ID = EMLS_ECG.STRING_ID
				AND ECG.COMPANYGROUPTYPE_ID = 1) COMPANY_INDUSTRY,
				(SELECT EA.AGREEMENT_ID,
				EMFTR.A_BASERANGE || ' - ' || EMFTR.N_PERCENTAGE * 100 || ' %' AS N_PERCENTAGE
				FROM E_AGREEMENT EA,
				E_BILLING_RULE EBR,
				E_BILLING_RULE_SET EBRS,
				E_BILLING_RULE_SET_BILL_RULE EBRSBR,
				E_FACE_VALUE_BILL_RULE EFVBR,
				E_MONEY_FILTER_TABLE EMFT,
				E_MONEY_FILTER_TABLE_ROW EMFTR
				WHERE EA.BILLINGRULESET_ID = EBRS.BILLINGRULESET_ID
				AND EBRS.BILLINGRULESET_ID = EBRSBR.BILLINGRULESET_ID
				AND EBRSBR.BILLINGRULE_ID = EBR.BILLINGRULE_ID
				AND EBR.BILLABLEITEMCATEGORY_ID = 5
				AND EBR.BILLINGRULE_ID = EFVBR.BILLINGRULE_ID
				AND EFVBR.MONEYFILTERTABLE_ID = EMFT.MONEYFILTERTABLE_ID
				AND EMFT.MONEYFILTERTABLE_ID = EMFTR.MONEYFILTERTABLE_ID) MARKETING_FEE,
				(SELECT EBDM.MEANOFPAYMENT_ID,
				EMLS_EB.DEFAULTVALUE,
				EMLS_EBDT.DEFAULTVALUE AS ACCOUNTTYPE,
				EBA.BANKACCOUNTNUMBER
				FROM E_BANK EB,
				E_BANK_ACCOUNT EBA,
				E_BANK_DEPOSIT_MOP EBDM,
				E_BANK_DEPOSIT_TYPE EBDT,
				E_MULTI_LANGUAGE_STRING EMLS_EB,
				E_MULTI_LANGUAGE_STRING EMLS_EBDT
				WHERE EBDM.BANKACCOUNT_ID = EBA.BANKACCOUNT_ID
				AND EBA.BANK_ID = EB.BANK_ID
				AND EB.NAME_ID = EMLS_EB.STRING_ID
				AND EBDM.BANKDEPOSITTYPE_ID = EBDT.BANKDEPOSITTYPE_ID
				AND EBDT.NAME_ID = EMLS_EBDT.STRING_ID) BANK_INFO
				WHERE EAA.AGREEMENT_ID = EA.AGREEMENT_ID
				AND EA.COMPANY_ID = EC.COMPANY_ID
				AND EC.COMPANYGENERALDATA_ID = ECGD.COMPANYGENERALDATA_ID
				AND ECGD.COMPANYGENERALDATA_ID = ECGDP.COMPANYGENERALDATA_ID
				AND ECGD.FISCAL_ID = COMPANY_INDUSTRY.FISCAL_ID(+)
				AND EA.AGREEMENTGENERALDATA_ID = EAGD.AGREEMENTGENERALDATA_ID
				AND EA.SERVICE_ID = ES.SERVICE_ID
				AND ES.NAME_ID = EMLS_ES.STRING_ID
				AND EA.AGREEMENT_ID = MARKETING_FEE.AGREEMENT_ID(+)
				AND EAA.REIMBURSEMENTCONDITIONS_ID = EFC.FINANCIALCONDITION_ID
				AND EFC.FINANCIALCONDITION_ID = EFCP.FINANCIALCONDITION_ID
				AND EFC.DAYSCOUNTINGTYPE_ID = EDCT.DAYSCOUNTINGTYPE_ID
				AND EDCT.NAME_ID = EMLS_EDCT.STRING_ID
				AND EFC.MEANOFPAYMENT_ID = EMOP.MEANOFPAYMENT_ID
				AND EMOP.MEANOFPAYMENTTYPE_ID = EMOPT.MEANOFPAYMENTTYPE_ID
				AND EMOPT.NAME_ID = EMLS_EMOPT.STRING_ID
				AND EMOP.MEANOFPAYMENT_ID = BANK_INFO.MEANOFPAYMENT_ID(+)
				AND EFCP.PAYMENTSUBMISSIONTYPE_ID = EPSTP.PAYMENTSUBMISSIONTYPE_ID
				AND EPSTP.NAME_ID = EMLS_EPSTP.STRING_ID
				AND EA.AGREEMENT_ID = EIP.AGREEMENT_ID
				AND EC.B_ACTIVE = 'T'
				AND ECGD.B_MOBILEVOUCHERPARTNER = 'T'
				and EA.SERVICE_ID = 27
				".$where."
				ORDER BY EC.COMPANY_ID
		)
		GROUP BY 
			CP_ID,
			TIN,
			LegalName, 
			TradingName,
			GroupTIN,
			GroupName,
			MerchantFee,
			VATCond,
			Industry,
			MeanofPayment,
			BankName,
			BankAccountNumber,
			PayeeName,
			PayeeCode,
			PayeeId,
			AffiliateGroupCode,
			PayeeQtyOfDays,
			PayeeDayType,
			PayeeComments,
			Address
		ORDER BY CP_ID ASC");
		return $result;
	}
	
	///---------------- FILTER FOR SALESFORCE CHECKER -----------------------------------

	
	/**
	 * getQueryDeliveryPoint function
	 *
	 * QUERY ACTION FOR COREPASS AGREEMENT DELIVERY POINT
	 */
	public function getQueryDelPoint($agrID){
		if(empty($agrID)) return '';
		$result = $this->oracle_db->query("select 
			EDN2.DELIVERYNODE_ID AS deliveryPointsId,
			EDN2.DELIVERYNODENAME AS deliveryPointsName
			from
			E_DELIVERY_NODE EDN,
			E_DELIVERY_NODE EDN2,
			E_VOUCHER_CUST_AGREEMENT EVCA
			where 
			EVCA.DELIVERYNODE_ID = EDN.DELIVERYNODE_ID
			AND EDN.DELIVERYNODE_ID = EDN2.PARENT_ID
			AND EVCA.AGREEMENT_ID = $agrID");
		return $result;
	}
	
	/**
	 * getQueryAgrSpRole function
	 *
	 * QUERY ACTION FOR COREPASS AGREEMENT SPROLE ID
	 */
	public function getQueryAgrSpRole($agrID){
		if(empty($agrID)) return '';
		$result = $this->oracle_db->query("SELECT 
			EA.AGREEMENT_ID AGREEMENT_ID, SUB4_ar.AGREEMENTROLE_ID SPROLE_ID
			FROM
			E_COMPANY EC,
			E_AGREEMENT EA,
			E_AGREEMENT_ROLE_SET_AGR_ROLE SUB4_arsar,
			E_AGREEMENT_ROLE SUB4_ar
			,E_GROUP_PEOPLE SUB4_gp  
			,E_COMPANY_PERSON SUB4_cp 
			,E_PHYSICAL_PERSON SUB4_pp
			WHERE
			EC.COMPANY_ID = EA.COMPANY_ID
			AND EC.B_ACTIVE = 'T'
			AND EA.B_ACTIVE = 'T'
			and SUB4_AR.AGREEMENTROLETYPE_ID = 4
			AND SUB4_arsar.agreementroleset_id = EA.agreementroleset_id
			and SUB4_ARSAR.AGREEMENTROLE_ID=SUB4_AR.AGREEMENTROLE_ID
			and SUB4_AR.PEOPLE_ID=SUB4_GP.GROUP_ID
			and SUB4_GP.PEOPLE_ID=SUB4_CP.PEOPLE_ID
			and SUB4_PP.PHYSICALPERSON_ID=SUB4_CP.PHYSICALPERSON_ID
			and EA.AGREEMENT_ID = $agrID");
		return $result;
	}
	
	/**
	 * getQueryAcctPeopleID function
	 *
	 * QUERY ACTION FOR COREPASS ACCOUNT PEOPLE ID
	 */
	public function getQueryAcctPeopleID($acctID){
		if(empty($acctID)) return '';
		$result = $this->oracle_db->query("SELECT 
		CP.COMPANY_ID, 
		CP.PEOPLE_ID AS PEOPLE_ID, 
		FP.NAME AS FIRST_NAME, FP.LASTNAME AS LAST_NAME
		FROM E_COMPANY_PERSON CP
		INNER JOIN E_PHYSICAL_PERSON FP ON CP.PHYSICALPERSON_ID = FP.PHYSICALPERSON_ID
		WHERE CP.COMPANY_ID = $acctID AND CP.B_ACTIVE = 'T'
		ORDER BY CP.PEOPLE_ID ASC");
		return $result;
	}
	/**
	 * getQueryAcctSpRoleID function
	 *
	 * QUERY ACTION FOR COREPASS ACCOUNT SPROLE ID
	 */
	public function getQueryAcctSpRoleID($acctID){
		if(empty($acctID)) return '';
		$result = $this->oracle_db->query("SELECT 
			EC.COMPANY_ID,
			SUB4_AR.AGREEMENTROLE_ID SP_ROLEID,
			SUB4_PP.NAME || ' ' || SUB4_PP.LASTNAME NAME,
			SUB4_CP.PEOPLE_ID SP_PEOPLEID,
			SUB4_AR.AGREEMENTROLETYPE_ID  ROLE_TYPEID
			FROM
			E_COMPANY EC
			,E_COMPANY_GENERAL_DATA ECGD
			,E_AGREEMENT_ROLE_SET_AGR_ROLE SUB4_arsar
			,E_AGREEMENT_ROLE SUB4_ar
			,E_GROUP_PEOPLE SUB4_gp  
			,E_COMPANY_PERSON SUB4_cp 
			,E_PHYSICAL_PERSON SUB4_pp
			WHERE
			EC.AGREEMENTROLESET_ID=SUB4_arsar.AGREEMENTROLESET_ID
			AND EC.COMPANYGENERALDATA_ID = ECGD.COMPANYGENERALDATA_ID
			and SUB4_ARSAR.AGREEMENTROLE_ID=SUB4_AR.AGREEMENTROLE_ID
			and SUB4_AR.AGREEMENTROLETYPE_ID IN (4, 110)-- Account Manager
			and SUB4_AR.PEOPLE_ID=SUB4_GP.GROUP_ID
			and SUB4_GP.PEOPLE_ID=SUB4_CP.PEOPLE_ID
			and SUB4_PP.PHYSICALPERSON_ID=SUB4_CP.PHYSICALPERSON_ID
			and EC.COMPANY_ID = $acctID
			order by EC.COMPANY_ID asc");
		return $result;
	}

	/**
	 * getQueryContactDataID function
	 *
	 * QUERY ACTION FOR COREPASS ACCOUNT CONTACT DATA ID
	 */
	public function getQueryContactDataID($acctID){
		if(empty($acctID)) return '';
		$result = $this->oracle_db->query("SELECT DISTINCT ECD.CONTACTDATA_ID AS contactDataId,
			EC.COMPANY_ID as companyId,
			ECD.CONTACTDATATYPE_ID as contactDataTypeId,
			EMLS_ECD.DEFAULTVALUE AS contactDataTypeName,
			ECDSCD.CONTACTDATASET_ID as contactDataSetId, 
			EPCD.THOROUGHFAREDEPENDENT AS description
			FROM 
			E_COMPANY EC,
			E_CONTACT_DATA_SET ECDS,
			E_CONT_DATA_SET_CONT_DATA ECDSCD,
			E_CONTACT_DATA ECD,
			E_CONTACT_DATA_TYPE ECDT,
			E_POSTAL_CONTACT_DATA EPCD,
			E_THOROUGHFARE_TYPE TFT,
			E_REGION ER1,
			E_REGION ER2,
			E_REGION ER3,
			E_MULTI_LANGUAGE_STRING EMLS_ER1,
			E_MULTI_LANGUAGE_STRING EMLS_ER2,
			E_MULTI_LANGUAGE_STRING EMLS_ER3,
			E_MULTI_LANGUAGE_STRING EMLS_ECD,
			E_MULTI_LANGUAGE_STRING EMLS_TFT
			WHERE 
			EC.COMPANYGENERALDATA_ID = ECDS.CONTACTDATASET_ID
			AND ECDS.CONTACTDATASET_ID = ECDSCD.CONTACTDATASET_ID
			AND ECDSCD.CONTACTDATA_ID = ECD.CONTACTDATA_ID
			AND ECD.CONTACTDATA_ID = EPCD.CONTACTDATA_ID
			AND ECD.CONTACTDATATYPE_ID = ECDT.CONTACTDATATYPE_ID
			AND ECDT.NAME_ID = EMLS_ECD.STRING_ID
			AND EPCD.LOCALITY = ER1.REGION_ID
			AND ER1.NAME_ID = EMLS_ER1.STRING_ID
			AND ER1.PARENT_ID = ER2.REGION_ID
			AND ER2.NAME_ID = EMLS_ER2.STRING_ID
			AND ER2.PARENT_ID = ER3.REGION_ID
			AND ER3.NAME_ID = EMLS_ER3.STRING_ID
			AND EPCD.THOROUGHFARETYPE_ID = TFT.THOROUGHFARETYPE_ID
			AND TFT.NAME_ID = EMLS_TFT.STRING_ID
			AND ECD.CONTACTDATATYPE_ID = 1 --(1:address, 2:phone, 4:email)
			AND EPCD.B_ACTIVE = 'T'
			AND EC.B_ACTIVE = 'T'
			AND EC.COMPANY_ID = $acctID
			ORDER BY EC.COMPANY_ID ASC");
		return $result;
	}
	
	/**
	 * getQueryAgreementRole function
	 *
	 * QUERY ACTION FOR COREPASS CLIENT
	 */
	public function getQueryAgreementRole($AGREEMENT_ID){
		/**
		 * 
		 */		 
		$result = $this->oracle_db->query("SELECT EA.AGREEMENT_ID,
				EAR.X_AGREEMENTROLE,
				EAR.COMMENTS,
				EGP.PEOPLE_ID,
				EPP.NAME || ' ' || EPP.lastname as FULLNAME,
				PHONE.CONTACT
				FROM 
				E_AFFILIATE_AGREEMENT EAA,
				E_AGREEMENT EA,
				E_AGREEMENT_ROLE EAR,
				E_AGREEMENT_ROLE_SET_AGR_ROLE EARSAR,
				E_GROUP_PEOPLE EGP,
				E_COMPANY_PERSON ECP,
				E_PHYSICAL_PERSON EPP,
				(
					select 
					cd.CONTACTDATA_ID,
					cdscd.CONTACTDATASET_ID,
					SCD.CONTACT
					from  
					E_CONTACT_DATA_SET cds,
					E_CONT_DATA_SET_CONT_DATA cdscd,
					E_CONTACT_DATA cd,
					E_SIMPLE_CONTACT_DATA scd
					where cds.CONTACTDATASET_ID = cdscd.CONTACTDATASET_ID
					and cdscd.CONTACTDATA_ID = cd.CONTACTDATA_ID
					and cd.CONTACTDATA_ID = scd.CONTACTDATA_ID
					and CD.CONTACTDATATYPE_ID = 2
				 ) PHONE
				WHERE 
				EA.AGREEMENT_ID = $AGREEMENT_ID
				AND EAA.AGREEMENT_ID = EA.AGREEMENT_ID
				AND EA.AGREEMENTROLESET_ID = EARSAR.AGREEMENTROLESET_ID
				and EARSAR.AGREEMENTROLE_ID=EAR.AGREEMENTROLE_ID
				and EAR.AGREEMENTROLETYPE_ID = 109
				and EAR.PEOPLE_ID = EGP.GROUP_ID
				AND EGP.PEOPLE_ID = ECP.PEOPLE_ID
				AND ECP.PHYSICALPERSON_ID = EPP.PHYSICALPERSON_ID
				and EAR.CONTACTDATASET_ID = PHONE.CONTACTDATASET_ID (+)");
		return $result;
	}

} //END CLASS

