CREATE TABLE `refund` (
  `REFUND_ID` int(11) NOT NULL,
  `REDEEM_ID` varchar(50) NOT NULL,
  `REVERSAL_TRANSACTION_ID` varchar(100) NOT NULL,
  `TRANSACTION_ID` varchar(50) NOT NULL,
  `RECON_ID` varchar(50) NOT NULL,
  `REVERSAL_MODE` varchar(50) NOT NULL,
  `PROD_ID` int(11) NOT NULL,
  `REDEEM_STATUS` varchar(50) NOT NULL,
  `MERCHANT_ID` int(11) NOT NULL,
  `BRANCH_ID` varchar(25) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `UPLOAD_ID` int(11) NOT NULL,
  `REVERSAL_DATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_CREATED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `PA_ID` int(11) NOT NULL COMMENT 'adjustment PA'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `refund`
  ADD PRIMARY KEY (`REFUND_ID`),
  ADD UNIQUE KEY `redeem_id` (`REDEEM_ID`),
  ADD KEY `upload_id` (`UPLOAD_ID`),
  ADD KEY `recon_id` (`RECON_ID`),
  ADD KEY `merchant_id` (`MERCHANT_ID`),
  ADD KEY `branch_id` (`BRANCH_ID`),
  ADD KEY `user_id` (`USER_ID`),
  ADD KEY `PA_ID` (`PA_ID`),
  ADD KEY `REVERSAL_TRANSACTION_ID` (`REVERSAL_TRANSACTION_ID`),
  ADD KEY `TRANSACTION_ID` (`TRANSACTION_ID`),
  ADD KEY `PROD_ID` (`PROD_ID`),
  ADD KEY `RECON_ID_2` (`RECON_ID`);

ALTER TABLE `refund`
  MODIFY `REFUND_ID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;