CREATE TABLE `temp_refund` (
  `TEMP_REFUNDID` int(11) NOT NULL,
  `REFUND_ID` int(11) NOT NULL,
  `MERCHANT_NAME` varchar(250) NOT NULL,
  `MERCHANT_ID` varchar(250) NOT NULL,
  `BRANCH_ID` varchar(250) NOT NULL,
  `POS_ID` varchar(250) NOT NULL,
  `POS_TXN_ID` varchar(250) NOT NULL,
  `PROD_ID` varchar(250) NOT NULL,
  `TRANSACTION_DATE_TIME` varchar(250) NOT NULL,
  `TRANSACTION_ID` varchar(250) NOT NULL,
  `REDEMPTION_API_TRANSACTION_ID` varchar(250) NOT NULL,
  `REVERSAL_DATE_TIME` varchar(250) NOT NULL,
  `REVERSAL_TRANSACTION_ID` varchar(250) NOT NULL,
  `VOUCHER_CODE` varchar(250) NOT NULL,
  `TRANSACTION_VALUE` varchar(250) NOT NULL,
  `RECON_API_TRANSACTION_ID` varchar(250) NOT NULL,
  `PAYMENT_MODE` varchar(250) NOT NULL,
  `REVERSAL_MODE` varchar(250) NOT NULL,
  `UPLOAD_ID` int(11) NOT NULL,
  `DATE_CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ERROR_MESSAGE` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `temp_refund`
  ADD PRIMARY KEY (`TEMP_REFUNDID`),
  ADD KEY `REFUND_ID` (`REFUND_ID`),
  ADD KEY `UPLOAD_ID` (`UPLOAD_ID`);


ALTER TABLE `temp_refund`
  MODIFY `TEMP_REFUNDID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

